{
 "title": "Client Information",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests by Edge Location",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(x_edge_location) as count, \nx_edge_location as location\nFROM realtime_logs\nWHERE timestamp <= $__toTime AND timestamp >= $__fromTime\nGROUP BY x_edge_location\nORDER BY count DESC\n"
    }
   ]
  },
  {
   "title": "Requests by Client Country Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(c_country) as count, \nc_country as country\nFROM realtime_logs\nWHERE timestamp <= $__toTime AND timestamp >= $__fromTime\nGROUP BY country\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Requests By Client IP ",
   "type": "table",
   "description": "This graph shows the number of requests for IP addresses over time. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT c_ip, count(c_ip) count\nFROM canopy.\"realtime_logs\" \nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime\nGROUP BY c_ip\nORDER BY count DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Requests By Client IP Over Time",
   "type": "timeseries",
   "description": "This graph shows the number of requests for IP addresses over time. ",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, c_ip, count(c_ip) Client_Ip FROM canopy.\"realtime_logs\" WHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) GROUP BY c_ip, time ORDER BY time ASC LIMIT 100"
    }
   ]
  },
  {
   "title": "Requests by Edge Location Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL (($__toTime - $__fromTime) / 20) SECOND ) AS d,\ncount(x_edge_location) as count, \nx_edge_location as location\nFROM realtime_logs\nWHERE timestamp <= $__toTime AND timestamp >= $__fromTime\nGROUP BY d, location\nORDER BY d, count ASC\n"
    }
   ]
  },
  {
   "title": "Total Requests by Content Type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sc_content_type AS TYPE, \ncount(sc_content_type) AS count\nFROM canopy.\"realtime_logs\" \nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime\nGROUP BY TYPE\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Top 10 URI by Status Code (2xx, 3xx)",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT cs_uri_stem AS URI, \ncount(cs_uri_stem) AS count,\nsc_status AS status\nFROM canopy.\"realtime_logs\" \nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime AND status >= 200 AND status <= 399\nGROUP BY cs_uri_stem, status\nORDER BY count DESC \nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 URI by Status Code (4xx, 5xx)",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT cs_uri_stem AS URI, \ncount(cs_uri_stem) AS count,\nsc_status AS status\nFROM canopy.\"realtime_logs\" \nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime AND status >= 400 AND status <= 599\nGROUP BY cs_uri_stem, status\nORDER BY count DESC \nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 URI by Cache Miss",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT cs_uri_stem AS URI, \ncount(cs_uri_stem) AS count,\nx_edge_result_type AS edge\nFROM canopy.\"realtime_logs\" \nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime AND edge = 'Miss'\nGROUP BY cs_uri_stem, x_edge_result_type\nORDER BY count DESC \nLIMIT 10"
    }
   ]
  },
  {
   "title": "Total Requests by Referer",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT cs_referer AS REFERER, \ncount(cs_referer) AS count\nFROM canopy.\"realtime_logs\" \nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime\nGROUP BY REFERER\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Requests by HTTP Method",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cs_method AS method,\ncount(method) AS count\nFROM realtime_logs\nWHERE timestamp <= $__toTime AND timestamp >= $__fromTime\nGROUP BY method\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Requests by HTTP Protocol / Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cs_protocol AS protocol,\ncs_protocol_version AS version,\ncount(cs_protocol_version) AS count\nFROM realtime_logs\nWHERE timestamp <= $__toTime AND timestamp >= $__fromTime\nGROUP BY protocol, version\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Requests by Client Port (top 20)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT c_port as port,\ncount(c_port) as count\nFROM realtime_logs\nWHERE timestamp <= $__toTime AND timestamp >= $__fromTime\nGROUP BY port\nORDER BY count DESC\nLIMIT 20\n"
    }
   ]
  },
  {
   "title": "Total Requests by User Agent",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT cs_user_agent AS AGENT, \ncount(cs_user_agent) AS count\nFROM canopy.\"realtime_logs\" \nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime\nGROUP BY AGENT\nORDER BY count DESC"
    }
   ]
  }
 ]
}