{
 "title": "CDN Logs Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cache-Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Success Rate (2xx, 3xx)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Error Rate (4xx)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(timestamp) FROM \"realtime_logs\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )"
    }
   ]
  },
  {
   "title": "Total Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(timestamp) FROM \"realtime_logs\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( x_edge_result_type = 'Hit' )"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(timestamp) FROM \"realtime_logs\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( sc_status != 200 )"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(timestamp) AS c,\n  toStartOfInterval(timestamp, INTERVAL (($__toTime - $__fromTime) / 36) SECOND ) AS d\nFROM realtime_logs\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nAND x_edge_result_type = 'Hit'\nGROUP BY d\nORDER BY d ASC"
    },
    {
     "rawSql": "SELECT\n  count(timestamp) AS c,\n  toStartOfInterval(timestamp, INTERVAL (($__toTime - $__fromTime) / 36) SECOND ) AS d\nFROM realtime_logs\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nAND x_edge_result_type = 'Miss'\nGROUP BY d\nORDER BY d ASC"
    }
   ]
  },
  {
   "title": "HTTP Status code distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nsc_status as category,\ncount(sc_status)\nFROM canopy.\"realtime_logs\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) \nGROUP BY category\nORDER BY category",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Total Bandwidth (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(sc_bytes) AS content_bytes,\n  sum(cs_bytes) AS client_bytes,\n  toStartOfInterval(timestamp, INTERVAL (($__toTime - $__fromTime) / 20) SECOND ) AS d\nFROM realtime_logs\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nGROUP BY d\nORDER BY d ASC"
    }
   ]
  },
  {
   "title": "Top 10 URI By Request",
   "type": "table",
   "description": "This table shows a list of the top 10 URIs by request, irrespective of whether the request result was a hit or miss.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT cs_uri_stem URI, count(*) Count FROM canopy.\"realtime_logs\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) GROUP BY cs_uri_stem ORDER BY count(*) DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Canopy Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT log, timestamp FROM canopy.\"realtime_logs\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) ORDER BY timestamp ASC LIMIT 500"
    }
   ]
  }
 ]
}