{
 "title": "Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Time Taken (Avg/95th)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL (($__toTime - $__fromTime) / 20) SECOND ) AS d,\nquantile(0.95)(time_taken) AS `95 Percentile`,\navg(time_taken) `Average` \nFROM \"realtime_logs\"\nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime\nGROUP BY d ORDER BY d ASC"
    }
   ]
  },
  {
   "title": "Time Taken by Response Code (Avg/95th)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL (($__toTime - $__fromTime) / 20) SECOND ) AS d,\nquantile(0.95)(time_taken) AS `95 Percentile`,\ntoString(sc_status) AS status,\navg(time_taken) `Average` \nFROM \"realtime_logs\"\nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime\nGROUP BY status, d ORDER BY d, `95 Percentile` DESC"
    }
   ]
  },
  {
   "title": "Time Taken by Edge Location (Avg/95th)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL (($__toTime - $__fromTime) / 20) SECOND ) AS d,\nquantile(0.95)(time_taken) AS `95 Percentile`,\nx_edge_location AS location,\navg(time_taken) `Average` \nFROM \"realtime_logs\"\nWHERE timestamp  >= $__fromTime AND timestamp <= $__toTime\nGROUP BY d, location ORDER BY d, `95 Percentile` DESC"
    }
   ]
  },
  {
   "title": "Time Taken by 10 slowest URIs (Avg/95th) over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL (($__toTime - $__fromTime) / 20) SECOND ) AS d,\navg(time_taken) AS avg,\nquantile(0.95)(time_taken) AS `95 Percentile`,\ncs_uri_stem FROM realtime_logs\nWHERE cs_uri_stem IN \n(SELECT cs_uri_stem from (\n  SELECT cs_uri_stem\n  from realtime_logs\n) table1 JOIN \n(\n  SELECT DISTINCT cs_uri_stem,\n  sum(time_taken)\n  FROM \"realtime_logs\"\n  WHERE timestamp  >= $__fromTime AND timestamp <= $__toTime\n  GROUP BY cs_uri_stem, time_taken\n  ORDER BY time_taken DESC\n  LIMIT 10\n) table2\nON \ntable1.cs_uri_stem = table2.cs_uri_stem)\nGROUP BY cs_uri_stem, d\nORDER BY d ASC"
    }
   ]
  },
  {
   "title": "TLS Versions and Cipher",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ssl_protocol AS protocol,\nssl_cipher AS cipher,\ncount(protocol) AS count\nFROM realtime_logs\nWHERE timestamp <= $__toTime AND timestamp >= $__fromTime\nGROUP BY protocol, cipher\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Bytes Transferred Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(sc_bytes) AS b,\n  toStartOfInterval(timestamp, INTERVAL 1 MINUTE) AS d\nFROM realtime_logs\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nGROUP BY d\nORDER BY d ASC"
    }
   ]
  }
 ]
}